-- ============================================================
-- 1. NETTOYAGE (DROP TABLES)
-- ============================================================

-- Suppression des tables (Ordre : Filles -> Mères)
DROP TABLE LigneCommandeProduit CASCADE CONSTRAINTS;
DROP TABLE LigneCommandeContenant CASCADE CONSTRAINTS;
DROP TABLE CommandeàLivrer CASCADE CONSTRAINTS;
DROP TABLE CommandeenBoutique CASCADE CONSTRAINTS;
DROP TABLE ProduitAPourCaractéristique CASCADE CONSTRAINTS;
DROP TABLE ProduitAPourSaison CASCADE CONSTRAINTS;
DROP TABLE ProducteurAPourActivite CASCADE CONSTRAINTS;
DROP TABLE PerteProduit CASCADE CONSTRAINTS;
DROP TABLE PerteContenant CASCADE CONSTRAINTS;
DROP TABLE LotProduit CASCADE CONSTRAINTS;
DROP TABLE LotContenant CASCADE CONSTRAINTS;
DROP TABLE ProduitStock CASCADE CONSTRAINTS;
DROP TABLE ProduitCommande CASCADE CONSTRAINTS;
DROP TABLE Caractéristique CASCADE CONSTRAINTS;
DROP TABLE SaisonDisponibilité CASCADE CONSTRAINTS;
DROP TABLE ClientAPourAdresseLivraison CASCADE CONSTRAINTS;
DROP TABLE Commande CASCADE CONSTRAINTS;
DROP TABLE Client CASCADE CONSTRAINTS;
DROP TABLE ClientAnonyme CASCADE CONSTRAINTS;
DROP TABLE AdresseLivraison CASCADE CONSTRAINTS;
DROP TABLE Produit CASCADE CONSTRAINTS;
DROP TABLE Contenant CASCADE CONSTRAINTS;
DROP TABLE Producteur CASCADE CONSTRAINTS;
DROP TABLE Activité CASCADE CONSTRAINTS;
DROP TABLE AdressePComplete CASCADE CONSTRAINTS;

COMMIT;